### ISSUE TITLE
sound is not played.

### ISSUE THREAD

**Issue by mid787** [jbristowe/nativescript-sound#11]
var sound = require("nativescript-sound");

![image](https://user-images.githubusercontent.com/2842123/33803919-6c88c5f8-dda3-11e7-80b6-e81c0ca9723f.png)

No errors in console ( and if I put other non-existing  filename - then it shows an error : "file not found") - so it does see the file.

Why doesn't it play ? 

[manifest](https://gist.github.com/anonymous/25378aca9804236be6666a915e23a082)

tnsinfo : 
![image](https://user-images.githubusercontent.com/2842123/33803930-ad450b88-dda3-11e7-8e70-88d871090e4d.png)

**EDIT**

If I put 

      let tada = sound.create("~/raw/beep.mp3");

as a field  ( outside a function): 

   tada = sound.create("~/raw/beep.mp3");

then it does work.

I don't want to initialize it as a field.

is it possible to use it as a  psuedo : `Promise(loadFile).then(playFile)` ?

**Comment by mudlabs** [comment]
**I get the same results in Android.** 
Sound will not play unless it's been assigned to a global variable.

* NativeScript 3.4.0

**Comment by mudlabs** [comment]
@RoyiNamir I did a _little_ digging into `SoundPool`, which is the native Android class used in this plugin.

I think the issue here is that it's intended to be used for short sound effects. Like in games or UI interactions. And that it would be normal (or expected) that these sound effects would be assigned early on, like when your app loads.

`SoundPool` uses the `MediaPlayer` service to decode the audio file into 16-bit PCM mono or stereo stream. This takes time. And it seems to take longer for `MediaPlayer` to decode our files and prep them for use than it does for `sound.create(path)` to return our sound object.

So when we immediately call `sound.play()` we send a request to the object, that exists and is valid, but we get no audio because the audio file it points to has not yet completed its decode process.

This doesn't seem to be an issue for `iOS` which uses `AVAudioPlayer`, but I don't know why. Perhaps it's just faster than Android or has a Promise like async feature built in so it knows there's already been a request to play.

I did get it working without the global variable using `setTimeout` though.

```javascript
const frame = require("ui/frame");
const sound = require("nativescript-sound");

/*
The minimal delay period I could get working for both iOS and Android
was different, hence the delay variable.
*/
function makeNoise(path) {
  const delay = frame.topmost().ios ? 10 : 50;
  const noise = sound.create(path);
  setTimeout(() => {
    noise.play();
  }, delay);
};

exports.buttonClicked = args => {
  const file_to_play = args.object.getItemById("fileName").name;
  makeNoise(`~/raw/${file_to_play}.mp3`);
}
```
But this still did not work _100%_ of the time. Quickly tapping multiple times would result in the odd failure to play. Strangely this failure was most prevalent in iOS, which had no problem consistently playing via the implementation you had in your original post.

It's also a bad solution for performance because every time we tap that button we are creating a `new Sound` which then has to be decoded.

Declaring your sounds globally seems to be the simplest way here. Either individually or in a collection as mentioned in the [READ.me](https://github.com/jbristowe/nativescript-sound/blob/master/README.md).

But if you don't wont them hanging around in the global scope you could create a closure. Then you can create/retrieve sounds on the fly. And implement your own promises there.
